version: '3.4'


services:
  eventbooking.api:
    image: ${DOCKER_REGISTRY-}eventbooking
    build:
      context: .
      dockerfile: EventBooking.Api/Dockerfile

    ports:
      - 5005:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - api-data:/var/eventBooking/app
    networks:
      - eventbooking
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_eventbooking
    restart: always
    ports: 
     - 6378:6379
    networks:
      - eventbooking

networks: 
  eventbooking:
    driver: bridge

volumes:
  api-data: